import { shellEnvVars } from "@brains/core/env-schema";
import { directorySyncEnvSchema } from "@brains/directory-sync/env-schema";
import type { EnvVarDecl } from "@brains/utils/env-schema";

/**
 * Every env var a Relay install consumes, in the order operators see
 * them in env.schema.template (generated by scripts/sync-env-templates.ts).
 */
export const relayEnvSchema: EnvVarDecl[] = [
  ...shellEnvVars(),
  ...directorySyncEnvSchema,
];
