import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { generateIdentity, identityToRecipient } from "age-encryption";

import { pushSecretsToBackend, normalizePushTarget } from "./push-secrets";
import { runSubprocess, type RunCommand } from "./run-subprocess";

export interface AgeKeyBootstrapOptions {
  logger?: (message: string) => void;
  pushTo?: string | undefined;
  runCommand?: RunCommand | undefined;
}

export interface AgeKeyBootstrapResult {
  createdLocalKey: boolean;
  identityPath: string;
  agePublicKey: string;
}

export async function runPilotAgeKeyBootstrap(
  rootDir: string,
  options: AgeKeyBootstrapOptions = {},
): Promise<{ success: boolean; message?: string }> {
  try {
    const result = await bootstrapPilotAgeKey(rootDir, options);
    return {
      success: true,
      message: result.createdLocalKey
        ? `Age key ready at ${result.identityPath}`
        : `Age key already ready at ${result.identityPath}`,
    };
  } catch (error) {
    return {
      success: false,
      message:
        error instanceof Error ? error.message : "Age key bootstrap failed",
    };
  }
}

export async function bootstrapPilotAgeKey(
  rootDir: string,
  options: AgeKeyBootstrapOptions = {},
): Promise<AgeKeyBootstrapResult> {
  const logger = options.logger ?? console.log;
  const identityPath = join(rootDir, ".brains-ops", "age", "identity.txt");

  let createdLocalKey = false;
  let identity = "";
  let agePublicKey = "";

  if (existsSync(identityPath)) {
    identity = extractAgeIdentity(readFileSync(identityPath, "utf8"));
    agePublicKey = await identityToRecipient(identity);
  } else {
    mkdirSync(dirname(identityPath), { recursive: true, mode: 0o700 });
    identity = await generateIdentity();
    agePublicKey = await identityToRecipient(identity);
    writeFileSync(identityPath, formatAgeIdentityFile(identity, agePublicKey), {
      encoding: "utf8",
      mode: 0o600,
    });
    createdLocalKey = true;
  }

  updatePilotYamlAgePublicKey(join(rootDir, "pilot.yaml"), agePublicKey);

  const pushTarget = normalizePushTarget(options.pushTo);
  if (pushTarget) {
    await pushSecretsToBackend(
      pushTarget,
      [["AGE_SECRET_KEY", readFileSync(identityPath, "utf8")]],
      {
        logger,
        runCommand: options.runCommand ?? runSubprocess,
      },
    );
  }

  logger(
    createdLocalKey ? `Created ${identityPath}` : `Reusing ${identityPath}`,
  );
  logger(`Configured pilot.yaml agePublicKey ${agePublicKey}`);
  if (pushTarget) {
    logger(`Pushed AGE_SECRET_KEY to ${pushTarget}`);
  }

  return {
    createdLocalKey,
    identityPath,
    agePublicKey,
  };
}

function updatePilotYamlAgePublicKey(
  pilotYamlPath: string,
  agePublicKey: string,
): void {
  const current = readFileSync(pilotYamlPath, "utf8");
  const existingMatch = current.match(/^agePublicKey:\s*(.+)$/m);
  const normalizedExisting = existingMatch?.[1]
    ?.trim()
    .replace(/^['"]|['"]$/g, "");

  if (normalizedExisting === agePublicKey) {
    return;
  }

  if (
    normalizedExisting &&
    normalizedExisting !== "age1replace-with-your-public-key"
  ) {
    throw new Error(
      `pilot.yaml agePublicKey does not match local age identity (${normalizedExisting} !== ${agePublicKey})`,
    );
  }

  if (existingMatch) {
    writeFileSync(
      pilotYamlPath,
      current.replace(/^agePublicKey:\s*.+$/m, `agePublicKey: ${agePublicKey}`),
      "utf8",
    );
    return;
  }

  const next = current.endsWith("\n")
    ? `${current}agePublicKey: ${agePublicKey}\n`
    : `${current}\nagePublicKey: ${agePublicKey}\n`;
  writeFileSync(pilotYamlPath, next, "utf8");
}

export function extractAgeIdentity(contents: string): string {
  const line = contents
    .split(/\r?\n/)
    .map((entry) => entry.trim())
    .find((entry) => entry.startsWith("AGE-SECRET-KEY-"));

  if (!line) {
    throw new Error("Missing AGE-SECRET-KEY in age identity file");
  }

  return line;
}

function formatAgeIdentityFile(identity: string, agePublicKey: string): string {
  return [
    "# generated by brains-ops age-key:bootstrap",
    `# public key: ${agePublicKey}`,
    identity,
    "",
  ].join("\n");
}
