import { access, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

const starterFiles = {
  "pilot.yaml": `schemaVersion: 1
brainVersion: 0.1.1-alpha.12
model: rover
githubOrg: <github-org>
repoPrefix: rover-
contentRepoSuffix: -content
domainSuffix: .rover.example.com
preset: core
`,
  "cohorts/cohort-1.yaml": `members:
  - alice
`,
  "users/alice.yaml": `handle: alice
discord:
  enabled: false
`,
  "views/users.md": `<!-- generated by brains-ops; run \`brains-ops render <repo>\` after editing pilot.yaml/users/cohorts -->
`,
  "docs/onboarding-checklist.md": `# Onboarding Checklist

1. Fill in \`pilot.yaml\`.
2. Add or edit \`users/<handle>.yaml\`.
3. Add the user to a cohort in \`cohorts/*.yaml\`.
4. Run \`brains-ops render <repo>\`.
5. Run \`brains-ops onboard <repo> <handle>\`.
`,
  "docs/operator-playbook.md": `# Operator Playbook

Document known failure modes, recovery steps, and operator notes here.
`,
  "README.md": `# rover-pilot

Private desired-state repo for pilot rover onboarding.

## Commands

- \`brains-ops init <repo>\`
- \`brains-ops render <repo>\`
- \`brains-ops onboard <repo> <handle>\`
- \`brains-ops reconcile-cohort <repo> <cohort>\`
- \`brains-ops reconcile-all <repo>\`
`,
} satisfies Record<string, string>;

export async function initPilotRepo(rootDir: string): Promise<void> {
  await mkdir(rootDir, { recursive: true });

  for (const [relativePath, content] of Object.entries(starterFiles)) {
    const fullPath = join(rootDir, relativePath);
    await mkdir(dirname(fullPath), { recursive: true });
    await writeIfMissing(fullPath, content);
  }
}

async function writeIfMissing(
  filePath: string,
  content: string,
): Promise<void> {
  try {
    await access(filePath);
    return;
  } catch {
    await writeFile(filePath, content);
  }
}
