import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  loadPilotRegistry,
  type LoadPilotRegistryOptions,
} from "./load-registry";

const header =
  "| handle | cohort | model | preset | brainVersion | domain | repo | contentRepo | discord | repoStatus | deployStatus | dnsStatus | mcpStatus | snapshotStatus |";
const separator =
  "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |";

export async function writeUsersTable(
  rootDir: string,
  options: LoadPilotRegistryOptions = {},
): Promise<void> {
  const registry = await loadPilotRegistry(rootDir, options);
  const rows = registry.users.map((user) => {
    const discord = user.discordEnabled ? "on" : "off";

    return [
      user.handle,
      user.cohort,
      user.model,
      user.preset,
      user.brainVersion,
      user.domain,
      user.repo,
      user.contentRepo,
      discord,
      user.repoStatus,
      user.deployStatus,
      user.dnsStatus,
      user.mcpStatus,
      user.snapshotStatus,
    ];
  });

  const content = [
    "<!-- generated by rover-pilot; do not edit -->",
    "",
    header,
    separator,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
    "",
  ].join("\n");

  await mkdir(join(rootDir, "views"), { recursive: true });
  await writeFile(join(rootDir, "views", "users.md"), content);
}

async function main(): Promise<void> {
  const rootDir = process.argv[2] ?? process.cwd();
  await writeUsersTable(rootDir);
}

const entrypointPath = process.argv[1];
if (entrypointPath && fileURLToPath(import.meta.url) === entrypointPath) {
  await main();
}
