import { describe, expect, it } from "bun:test";
import {
  ENV_SCHEMA_HEADER,
  renderEnvSchemaSection,
  type EnvVarDecl,
} from "@brains/utils/env-schema";
import { resolveDefinitionEnvSchema } from "../src/lib/env-schema";
import { canonicalEnvSchema } from "../src/model/env-schema";

const DEFINITIONS: Array<{ definition: string; decls: EnvVarDecl[] }> = [
  { definition: "brain", decls: canonicalEnvSchema },
];

function renderModelSchema(decls: EnvVarDecl[]): string {
  return `${ENV_SCHEMA_HEADER}\n\n${renderEnvSchemaSection(decls)}`;
}

describe("env schema resolution", () => {
  it("uses the generated canonical schema when package lookup is unavailable", () => {
    const unavailableWorkspaceLookup = (): string => {
      throw new Error("workspace lookup unavailable");
    };

    const canonicalSchema = resolveDefinitionEnvSchema(
      "brain",
      unavailableWorkspaceLookup,
    );
    expect(canonicalSchema).toContain("AI_API_KEY=");
    expect(canonicalSchema).toContain("GIT_SYNC_TOKEN=");
    expect(canonicalSchema).toContain("DISCORD_BOT_TOKEN=");

    expect(
      resolveDefinitionEnvSchema("@acme/custom", unavailableWorkspaceLookup),
    ).toBe("");
  });

  it("matches the canonical composed env declarations exactly (drift guard)", () => {
    // The templates (and therefore the canonical fallback) are generated by
    // scripts/sync-env-templates.ts from the same declarations imported
    // here. If someone edits a template by hand or forgets to re-sync
    // after changing a service/plugin env-schema.ts, this fails.
    const unavailableWorkspaceLookup = (): string => {
      throw new Error("workspace lookup unavailable");
    };
    for (const { definition, decls } of DEFINITIONS) {
      expect(
        resolveDefinitionEnvSchema(definition, unavailableWorkspaceLookup),
      ).toBe(renderModelSchema(decls));
    }
  });

  it("declares each canonical variable at most once", () => {
    for (const { decls } of DEFINITIONS) {
      const names = decls.map((decl) => decl.name);
      expect(new Set(names).size).toBe(names.length);
    }
  });
});
