import { describe, expect, it } from "bun:test";
import {
  ENV_SCHEMA_HEADER,
  renderEnvSchemaSection,
  type EnvVarDecl,
} from "@brains/utils/env-schema";
import { roverEnvSchema } from "@brains/rover/src/env-schema";
import { rangerEnvSchema } from "@brains/ranger/src/env-schema";
import { relayEnvSchema } from "@brains/relay/env-schema";
import { resolveModelEnvSchema } from "../src/lib/env-schema";

const MODELS: Array<{ model: string; decls: EnvVarDecl[] }> = [
  { model: "rover", decls: roverEnvSchema },
  { model: "ranger", decls: rangerEnvSchema },
  { model: "relay", decls: relayEnvSchema },
];

function renderModelSchema(decls: EnvVarDecl[]): string {
  return `${ENV_SCHEMA_HEADER}\n\n${renderEnvSchemaSection(decls)}`;
}

describe("env schema resolution", () => {
  it("uses bundled built-in schemas when workspace lookup is unavailable", () => {
    const unavailableWorkspaceLookup = (): string => {
      throw new Error("workspace lookup unavailable");
    };

    const roverSchema = resolveModelEnvSchema(
      "rover",
      unavailableWorkspaceLookup,
    );
    expect(roverSchema).toContain("AI_API_KEY=");
    expect(roverSchema).not.toContain("CMS_CONTENT_REPO_PAT=");
    expect(roverSchema).toContain("ATPROTO_APP_PASSWORD=");
    expect(roverSchema).not.toContain("ATPROTO_IDENTIFIER=");
    expect(
      resolveModelEnvSchema("ranger", unavailableWorkspaceLookup),
    ).toContain("LINKEDIN_ORGANIZATION_ID=");
    expect(
      resolveModelEnvSchema("relay", unavailableWorkspaceLookup),
    ).not.toContain("DISCORD_BOT_TOKEN=");
  });

  it("matches each model's composed env declarations exactly (drift guard)", () => {
    // The templates (and therefore the bundled schemas) are generated by
    // scripts/sync-env-templates.ts from the same declarations imported
    // here. If someone edits a template by hand or forgets to re-sync
    // after changing a service/plugin env-schema.ts, this fails.
    const unavailableWorkspaceLookup = (): string => {
      throw new Error("workspace lookup unavailable");
    };
    for (const { model, decls } of MODELS) {
      expect(resolveModelEnvSchema(model, unavailableWorkspaceLookup)).toBe(
        renderModelSchema(decls),
      );
    }
  });

  it("declares each variable at most once per model", () => {
    for (const { decls } of MODELS) {
      const names = decls.map((decl) => decl.name);
      expect(new Set(names).size).toBe(names.length);
    }
  });
});
