version: '3.8'

services:
  personal-brain:
    build:
      context: ../..
      dockerfile: deploy/docker/runtime/Dockerfile
    image: personal-brain:latest
    container_name: personal-brain
    ports:
      - "3333:3333"
    volumes:
      - brain-data:/app/data
      - brain-repo:/app/brain-repo
      - brain-website:/app/website
    environment:
      - DATABASE_URL=file:/app/data/brain.db
      - DATA_DIR=/app/data
      - BRAIN_REPO_PATH=/app/brain-repo
      - PUBLIC_WEBSITE_PATH=/app/website
      - NODE_ENV=production
      # Add your API keys here or use .env file
      # - ANTHROPIC_API_KEY=your-key-here
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  brain-data:
  brain-repo:
  brain-website: