brain: "@brains/relay"

# Production instance
domain: recall.rizom.ai

# Permissions
anchors:
  - "matrix:@yeehaa:rizom.ai"

plugins:
  git-sync:
    repo: rizom-ai/team-brain-content
    authorName: Relay
    authorEmail: yeehaa@rizom.ai
  matrix:
    userId: "@teambot:rizom.ai"
    homeserver: https://matrix.rizom.ai
  webserver:
    productionDomain: https://recall.rizom.ai
