/**
 * Curated public surface for `@rizom/brain-ui`.
 *
 * Every symbol here has a consumer today, per the subpath curation rule in
 * docs/plans/plugin-interface-boundaries.md. `./index.ts` remains the internal
 * barrel and carries the full component set; adding to this file requires a
 * named consumer, an export-ledger entry, and a stable-API document update
 * in the same change.
 */

export {
  Alert,
  BackLink,
  Breadcrumb,
  CTASection,
  Card,
  CardHeader,
  CardImage,
  CardMetadata,
  CardTitle,
  ContentArchive,
  ContentList,
  CoverImage,
  DetailPageHeader,
  EmptyState,
  Footer,
  Head,
  HeadProvider,
  Header,
  ImageRendererProvider,
  KeyValueList,
  LinkButton,
  ListPageHeader,
  MarkdownContent,
  NewsletterSignup,
  OgCard,
  Pagination,
  PresentationLayout,
  SectionHeader,
  StatBadge,
  StatusBadge,
  SubjectsList,
  TagsList,
  ThemeToggle,
  WidgetActionLink,
  WidgetActions,
  WidgetEmptyState,
  WidgetFilter,
  WidgetList,
  WidgetListItem,
  WidgetMetaLine,
  WidgetPrimitiveEmptyState,
  WidgetStatusPill,
  WidgetTabs,
  WidgetTags,
  createWidgetInstanceId,
  cssVariables,
  formatDate,
  markdownToHtml,
  renderHighlightedText,
  splitWordmark,
  tagVariants,
  useMarkdownToHtml,
} from "./index";

export type {
  AlertProps,
  BackLinkProps,
  BreadcrumbItem,
  BreadcrumbProps,
  CTASectionProps,
  CardImageProps,
  CardMetadataProps,
  CardProps,
  CardTitleProps,
  ContentArchiveProps,
  CSSVariableProperties,
  ContentItem,
  ContentListProps,
  CoverImageProps,
  DetailPageHeaderProps,
  EmptyStateProps,
  HeadCollectorInterface,
  HeadProps,
  HeadProviderProps,
  HeaderProps,
  ImageRenderer,
  ImageRendererProviderProps,
  KeyValueItem,
  LinkButtonProps,
  ListPageHeaderProps,
  MarkdownContentProps,
  NewsletterSignupProps,
  OgCardProps,
  PaginationProps,
  PresentationLayoutProps,
  SectionHeaderProps,
  StatBadgeProps,
  StatusBadgeProps,
  SubjectsListProps,
  TagsListProps,
  ThemeToggleProps,
  WidgetDataAttributes,
  WidgetElementProps,
  WidgetFilterOption,
  WidgetTabDefinition,
} from "./index";
