import { shellEnvVars } from "@brains/core/env-schema";
import { directorySyncEnvSchema } from "@brains/directory-sync/env-schema";
import { discordEnvSchema } from "@brains/discord/env-schema";
import { atprotoEnvSchema } from "@brains/atproto/env-schema";
import { socialMediaEnvSchema } from "@brains/social-media/env-schema";
import { newsletterEnvSchema } from "@brains/newsletter/env-schema";
import { emailResendEnvSchema } from "@brains/email-resend/env-schema";
import { analyticsEnvSchema } from "@brains/analytics/env-schema";
import { stockPhotoEnvSchema } from "@brains/stock-photo/env-schema";
import type { EnvVarDecl } from "@brains/utils/env-schema";

/**
 * Every env var a Rover install consumes, in the order operators see
 * them in env.schema.template (generated by scripts/sync-env-templates.ts).
 */
export const roverEnvSchema: EnvVarDecl[] = [
  ...shellEnvVars(),
  ...directorySyncEnvSchema,
  ...discordEnvSchema,
  ...atprotoEnvSchema,
  ...socialMediaEnvSchema,
  ...newsletterEnvSchema,
  ...emailResendEnvSchema,
  ...analyticsEnvSchema,
  ...stockPhotoEnvSchema,
];
