services:
  brain:
    build:
      context: ../../..
      dockerfile: deploy/docker/Dockerfile
      args:
        APP_NAME: collective-brain
    image: ${DOCKER_IMAGE:-rizom-collective:latest}
    container_name: ${CONTAINER_NAME:-rizom-collective}
    ports:
      # MCP Server port
      - "${BRAIN_SERVER_PORT:-3333}:3333"
      # Webserver ports
      - "${WEBSITE_PREVIEW_PORT:-4321}:4321"
      - "${WEBSITE_PRODUCTION_PORT:-8080}:8080"
    volumes:
      # Essential volumes for persistence
      - ${DATA_VOLUME:-./data}:/app/data               # SQLite databases
      - ${BRAIN_DATA_VOLUME:-./brain-data}:/app/brain-data    # Markdown content
      - ${CACHE_VOLUME:-./cache}:/app/cache            # Embedding model cache
    env_file:
      # Load environment variables from .env.production file
      # This file should be created from .env.production.example
      - ${ENV_FILE:-.env.production}
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - brain-network

networks:
  brain-network:
    driver: bridge
    name: ${NETWORK_NAME:-rizom-collective-network}
