#!/usr/bin/env bun
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";

function findMonorepoRoot(): string {
  let dir = import.meta.dir;
  while (!existsSync(join(dir, "bun.lock"))) {
    const parent = join(dir, "..");
    if (parent === dir) throw new Error("Build must run from the monorepo");
    dir = parent;
  }
  return dir;
}

const monorepoRoot = findMonorepoRoot();
const schema = readFileSync(
  join(monorepoRoot, "packages", "brain-cli", "env.schema.template"),
  "utf-8",
).trimEnd();
const outputPath = join(
  import.meta.dir,
  "..",
  "src",
  "lib",
  "generated",
  "canonical-env-schema.ts",
);
const content = `// Generated by scripts/generate-canonical-env-schema.ts
// Do not edit by hand.

export const canonicalEnvSchema =
  ${JSON.stringify(schema)};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content);
console.log(`Generated ${outputPath}`);
