#!/usr/bin/env bun
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";

function findMonorepoRoot(): string {
  let dir = import.meta.dir;
  while (!existsSync(join(dir, "bun.lock"))) {
    const parent = join(dir, "..");
    if (parent === dir) {
      throw new Error("Build must run from the monorepo");
    }
    dir = parent;
  }
  return dir;
}

function readModelEnvSchema(monorepoRoot: string, model: string): string {
  const modelDir = join(monorepoRoot, "brains", model);
  const templatePath = join(modelDir, "env.schema.template");
  if (existsSync(templatePath)) {
    return readFileSync(templatePath, "utf-8").trimEnd();
  }

  const legacyPath = join(modelDir, ".env.schema");
  if (existsSync(legacyPath)) {
    return readFileSync(legacyPath, "utf-8").trimEnd();
  }

  throw new Error(`Missing env schema for model: ${model}`);
}

const monorepoRoot = findMonorepoRoot();
const outputPath = join(
  import.meta.dir,
  "..",
  "src",
  "lib",
  "generated",
  "bundled-model-env-schemas.ts",
);
const models = ["rover", "ranger", "relay"];

const entries = models
  .map(
    (model) =>
      `  ${model}: ${JSON.stringify(readModelEnvSchema(monorepoRoot, model))},`,
  )
  .join("\n");

const content = `// Generated by scripts/generate-bundled-model-env-schemas.ts
// Do not edit by hand.

export const bundledModelEnvSchemas = {
${entries}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content);
console.log(`Generated ${outputPath}`);
