/** Curated public plugin authoring surface. */

export {
  EntityPlugin,
  ServicePlugin,
  InterfacePlugin,
  MessageInterfacePlugin,
  basePluginConfigSchema,
  defineChannel,
  createTool,
  createResource,
  toolSuccess,
  toolError,
  parseConfirmationResponse,
  formatConfirmationPrompt,
  urlCaptureConfigSchema,
} from "@brains/plugins";

export type {
  BasePluginContext,
  IMessagingNamespace,
  IIdentityNamespace,
  IConversationsNamespace,
  IEvalNamespace,
  IInsightsNamespace,
  EntityPluginContext,
  IEntitiesNamespace,
  IEntityAINamespace,
  IPromptsNamespace,
  ServicePluginContext,
  IServiceTemplatesNamespace,
  IViewsNamespace,
  InterfacePluginContext,
  IPermissionsNamespace,
  IDaemonsNamespace,
  IToolsNamespace,
  IApiRoutesNamespace,
  IWebRoutesNamespace,
  IPluginsNamespace,
  IInterfaceConversationsNamespace,
  Plugin,
  PluginConfig,
  PluginConfigInput,
  Tool,
  Resource,
  ResourceTemplate,
  Prompt,
  ToolContext,
  ToolResponse,
  ToolVisibility,
  ToolConfirmation,
  BaseJobTrackingInfo,
  MessageJobTrackingInfo,
  Channel,
  DeriveEvent,
} from "@brains/plugins";

export type {
  PluginFactory,
  PluginConfig as BrainPluginConfig,
} from "@brains/app";
