import { describe, expect, it } from "bun:test";
import {
  AgentResponseSchema,
  ChatContextSchema,
} from "../../src/contracts/agent";
import {
  createPublicAgentNamespace,
  toPublicAgentResponse,
} from "../../src/base/public-agent-service";

describe("public agent contracts", () => {
  it("accepts speaker attribution in chat context", () => {
    expect(
      ChatContextSchema.parse({
        interfaceType: "discord",
        channelId: "thread-456",
        actor: {
          actorId: "discord:user-789",
          interfaceType: "discord",
          role: "user",
          displayName: "Mira Ops",
        },
        source: {
          messageId: "message-123",
          channelId: "channel-123",
          threadId: "thread-456",
          metadata: { guildId: "guild-123" },
        },
      }),
    ).toEqual({
      interfaceType: "discord",
      channelId: "thread-456",
      actor: {
        actorId: "discord:user-789",
        interfaceType: "discord",
        role: "user",
        displayName: "Mira Ops",
      },
      source: {
        messageId: "message-123",
        channelId: "channel-123",
        threadId: "thread-456",
        metadata: { guildId: "guild-123" },
      },
    });
  });

  it("accepts native text attachments in chat context", () => {
    expect(
      ChatContextSchema.parse({
        attachments: [
          {
            kind: "text",
            filename: "notes.md",
            mediaType: "text/markdown",
            content: "# Notes",
            sizeBytes: 7,
            source: { kind: "upload", id: "upload-123" },
          },
        ],
      }),
    ).toEqual({
      attachments: [
        {
          kind: "text",
          filename: "notes.md",
          mediaType: "text/markdown",
          content: "# Notes",
          sizeBytes: 7,
          source: { kind: "upload", id: "upload-123" },
        },
      ],
    });
  });

  it("accepts native file attachments in chat context", () => {
    const imageBytes = new Uint8Array([137, 80, 78, 71]);
    expect(
      ChatContextSchema.parse({
        attachments: [
          {
            kind: "file",
            filename: "robot.png",
            mediaType: "image/png",
            data: imageBytes,
            sizeBytes: imageBytes.byteLength,
            source: { kind: "upload", id: "upload-123" },
          },
        ],
      }),
    ).toEqual({
      attachments: [
        {
          kind: "file",
          filename: "robot.png",
          mediaType: "image/png",
          data: imageBytes,
          sizeBytes: imageBytes.byteLength,
          source: { kind: "upload", id: "upload-123" },
        },
      ],
    });
  });

  it("forwards native attachments through the public agent namespace", async () => {
    const calls: unknown[] = [];
    const agent = createPublicAgentNamespace({
      chat: async (_message, _conversationId, context) => {
        calls.push(context);
        return {
          text: "ok",
          usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
        };
      },
      confirmPendingAction: async () => ({
        text: "ok",
        usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
      }),
      invalidateAgent: () => {},
    });

    await agent.chat("Summarize", "conversation-1", {
      attachments: [
        {
          kind: "text",
          filename: "notes.md",
          mediaType: "text/markdown",
          content: "# Notes",
          source: { kind: "upload", id: "upload-123" },
        },
      ],
    });

    expect(calls).toEqual([
      {
        attachments: [
          {
            kind: "text",
            filename: "notes.md",
            mediaType: "text/markdown",
            content: "# Notes",
            source: { kind: "upload", id: "upload-123" },
          },
        ],
      },
    ]);
  });

  it("maps runtime agent responses to the stable public contract", () => {
    const attachmentCard = {
      kind: "attachment" as const,
      id: "attachment:report-1",
      jobId: "job-1",
      title: "Weekly export",
      description: "PDF export generated by a tool.",
      attachment: {
        mediaType: "application/pdf",
        url: "/media/documents/report-1",
        downloadUrl: "/media/documents/report-1?download=1",
        filename: "weekly-export.pdf",
        sizeBytes: 42_000,
        source: {
          entityType: "document",
          entityId: "report-1",
          attachmentType: "export",
        },
      },
    };
    const response = toPublicAgentResponse({
      text: "Done",
      toolResults: [
        {
          toolName: "search",
          args: { query: "rizom" },
          jobId: "job-1",
          data: { count: 2 },
        },
      ],
      cards: [
        {
          kind: "tool-approval",
          id: "approval:call-1",
          toolCallId: "call-1",
          toolName: "delete",
          input: { id: "item-1" },
          summary: "Delete item",
          state: "approval-requested",
        },
        attachmentCard,
      ],
      pendingConfirmations: [
        {
          id: "approval:call-1",
          toolCallId: "call-1",
          toolName: "delete",
          summary: "Delete item",
          args: { id: "item-1" },
        },
      ],
      usage: {
        promptTokens: 1,
        completionTokens: 2,
        totalTokens: 3,
      },
    });

    expect(AgentResponseSchema.parse(response)).toEqual({
      text: "Done",
      toolResults: [
        {
          toolName: "search",
          args: { query: "rizom" },
          jobId: "job-1",
          data: { count: 2 },
        },
      ],
      cards: [
        {
          kind: "tool-approval",
          id: "approval:call-1",
          toolCallId: "call-1",
          toolName: "delete",
          input: { id: "item-1" },
          summary: "Delete item",
          state: "approval-requested",
        },
        attachmentCard,
      ],
      pendingConfirmations: [
        {
          id: "approval:call-1",
          toolCallId: "call-1",
          toolName: "delete",
          summary: "Delete item",
          args: { id: "item-1" },
        },
      ],
      usage: {
        promptTokens: 1,
        completionTokens: 2,
        totalTokens: 3,
      },
    });
  });

  it("accepts source citation cards in the public response", () => {
    const response = toPublicAgentResponse({
      text: "According to the retrieved context...",
      cards: [
        {
          kind: "sources",
          id: "sources:agent-context",
          title: "Retrieved context",
          sources: [
            {
              id: "summary-1",
              title: "Relay decision summary",
              source: "conversation-memory",
              entityType: "summary",
              entityId: "summary-1",
              excerpt: "The team decided to use explicit memory retrieval.",
              provenance: { conversationId: "relay-conv" },
            },
          ],
        },
      ],
      usage: { promptTokens: 1, completionTokens: 2, totalTokens: 3 },
    });

    expect(AgentResponseSchema.parse(response).cards).toEqual([
      {
        kind: "sources",
        id: "sources:agent-context",
        title: "Retrieved context",
        sources: [
          {
            id: "summary-1",
            title: "Relay decision summary",
            source: "conversation-memory",
            entityType: "summary",
            entityId: "summary-1",
            excerpt: "The team decided to use explicit memory retrieval.",
            provenance: { conversationId: "relay-conv" },
          },
        ],
      },
    ]);
  });

  it("accepts action cards in the public response", () => {
    const response = toPublicAgentResponse({
      text: "Choose the next step.",
      cards: [
        {
          kind: "actions",
          id: "actions:onboarding",
          title: "Next steps",
          defaultOpen: true,
          actions: [
            {
              type: "prompt",
              id: "review-draft",
              label: "Review draft",
              prompt: "Show me the transformed draft.",
              description: "Ask Rover to open the draft in chat.",
            },
            {
              type: "event",
              id: "continue",
              label: "Continue",
              event: "NEXT",
              description: "Request the next playbook transition.",
            },
          ],
        },
      ],
      usage: { promptTokens: 1, completionTokens: 2, totalTokens: 3 },
    });

    expect(AgentResponseSchema.parse(response).cards).toEqual([
      {
        kind: "actions",
        id: "actions:onboarding",
        title: "Next steps",
        defaultOpen: true,
        actions: [
          {
            type: "prompt",
            id: "review-draft",
            label: "Review draft",
            prompt: "Show me the transformed draft.",
            description: "Ask Rover to open the draft in chat.",
          },
          {
            type: "event",
            id: "continue",
            label: "Continue",
            event: "NEXT",
            description: "Request the next playbook transition.",
          },
        ],
      },
    ]);
  });

  it("does not expose singular pendingConfirmation in the public response", () => {
    const response = toPublicAgentResponse({
      text: "Confirmation required.",
      pendingConfirmations: [
        {
          id: "approval:first",
          toolName: "delete",
          summary: "Delete first item",
          args: { id: "first" },
        },
      ],
      usage: {
        promptTokens: 1,
        completionTokens: 2,
        totalTokens: 3,
      },
    });

    expect("pendingConfirmation" in response).toBe(false);
    expect(
      response.pendingConfirmations?.map((confirmation) => confirmation.id),
    ).toEqual(["approval:first"]);
  });
});
