import type {
  Plugin,
  PluginTool,
  PluginResource,
  ServicePluginContext,
} from "@brains/plugins";
import { ServicePlugin } from "@brains/plugins";
import { z } from "@brains/utils";
import { createTemplate } from "@brains/templates";
import { productSchema, enrichedProductSchema } from "./schemas/product";
import { productAdapter } from "./adapters/product-adapter";
import { overviewSchema, overviewWithDataSchema } from "./schemas/overview";
import { overviewAdapter } from "./adapters/overview-adapter";
import { ProductsDataSource } from "./datasources/products-datasource";
import {
  ProductsPageTemplate,
  type ProductsPageProps,
} from "./templates/products-page";
import type { ProductsConfig, ProductsConfigInput } from "./config";
import { productsConfigSchema } from "./config";
import packageJson from "../package.json";

/**
 * Products Plugin
 * Manages product entities and provides a marketing-style overview page
 */
export class ProductsPlugin extends ServicePlugin<ProductsConfig> {
  constructor(config: ProductsConfigInput = {}) {
    super("products", packageJson, config, productsConfigSchema);
  }

  protected override async onRegister(
    context: ServicePluginContext,
  ): Promise<void> {
    // Register entity types
    context.entities.register("product", productSchema, productAdapter);
    context.entities.register(
      "products-overview",
      overviewSchema,
      overviewAdapter,
    );

    // Register datasource
    const dataSource = new ProductsDataSource(
      this.logger.child("ProductsDataSource"),
    );
    context.entities.registerDataSource(dataSource);

    // Register template
    // Routes are auto-generated by the site-builder from registered entity types
    const productsPageSchema = z.object({
      overview: overviewWithDataSchema,
      products: z.array(enrichedProductSchema),
    });

    context.templates.register({
      "product-list": createTemplate<
        z.infer<typeof productsPageSchema>,
        ProductsPageProps
      >({
        name: "product-list",
        description: "Products page — overview + brain model cards",
        schema: productsPageSchema,
        dataSourceId: "products:entities",
        requiredPermission: "public",
        layout: {
          component: ProductsPageTemplate,
          interactive: false,
        },
      }),
    });

    this.logger.info("Products plugin registered successfully");
  }

  protected override async getTools(): Promise<PluginTool[]> {
    return [];
  }

  protected override async getResources(): Promise<PluginResource[]> {
    return [];
  }
}

export function productsPlugin(config: ProductsConfigInput = {}): Plugin {
  return new ProductsPlugin(config);
}
