import { shellEnvVars } from "@brains/core/env-schema";
import { directorySyncEnvSchema } from "@brains/directory-sync/env-schema";
import { discordEnvSchema } from "@brains/discord/env-schema";
import { socialMediaEnvSchema } from "@brains/social-media/env-schema";
import { analyticsEnvSchema } from "@brains/analytics/env-schema";
import type { EnvVarDecl } from "@brains/utils/env-schema";

/**
 * Every env var a Ranger install consumes, in the order operators see
 * them in env.schema.template (generated by scripts/sync-env-templates.ts).
 */
export const rangerEnvSchema: EnvVarDecl[] = [
  ...shellEnvVars(),
  ...directorySyncEnvSchema,
  ...discordEnvSchema,
  ...socialMediaEnvSchema,
  ...analyticsEnvSchema,
];
