import { describe, expect, it } from "bun:test";
import {
  artifactStatusLabel,
  formatArtifactDisplay,
  formatByteSize,
  getArtifactCardState,
  narrowArtifactJobStatus,
} from "../../src/message-interface/artifact-display";

describe("formatArtifactDisplay", () => {
  it("normalizes generated artifact cards for rendering", () => {
    expect(
      formatArtifactDisplay({
        kind: "attachment",
        id: "attachment:report-1",
        jobId: "job-1",
        title: "Weekly export",
        description: "PDF export generated by a tool.",
        attachment: {
          mediaType: "application/pdf",
          url: "/media/documents/report-1",
          downloadUrl: "/media/documents/report-1?download=1",
          previewUrl: "/media/documents/report-1/preview",
          filename: "weekly-export.pdf",
          sizeBytes: 42_000,
        },
      }),
    ).toEqual({
      jobId: "job-1",
      title: "Weekly export",
      description: "PDF export generated by a tool.",
      mediaType: "application/pdf",
      filename: "weekly-export.pdf",
      sizeLabel: "41 KB",
      url: "/media/documents/report-1",
      downloadUrl: "/media/documents/report-1?download=1",
      previewUrl: "/media/documents/report-1/preview",
    });
  });

  it("returns null for malformed attachment data", () => {
    expect(formatArtifactDisplay({ title: "Missing body" })).toBeNull();
  });

  it("falls back to a generic title", () => {
    expect(
      formatArtifactDisplay({
        attachment: { url: "/file", mediaType: "image/png" },
      }),
    ).toEqual({
      title: "Generated artifact",
      mediaType: "image/png",
      url: "/file",
    });
  });
});

describe("formatByteSize", () => {
  it("formats byte sizes for artifact metadata", () => {
    expect(formatByteSize(undefined)).toBeUndefined();
    expect(formatByteSize(-1)).toBeUndefined();
    expect(formatByteSize(42)).toBe("42 B");
    expect(formatByteSize(1536)).toBe("1.5 KB");
    expect(formatByteSize(42_000)).toBe("41 KB");
    expect(formatByteSize(5_500_000)).toBe("5.2 MB");
  });
});

describe("artifact status display", () => {
  it("uses explicit generated artifact status labels", () => {
    expect(artifactStatusLabel(null)).toBe("ready");
    expect(artifactStatusLabel("pending")).toBe("queued");
    expect(artifactStatusLabel("processing")).toBe("generating");
    expect(artifactStatusLabel("completed")).toBe("ready");
    expect(artifactStatusLabel("failed")).toBe("failed");
    expect(artifactStatusLabel("unknown")).toBe("status unknown");
  });

  it("narrows unknown job statuses", () => {
    expect(narrowArtifactJobStatus("processing")).toBe("processing");
    expect(narrowArtifactJobStatus("bogus")).toBe("unknown");
    expect(narrowArtifactJobStatus(undefined)).toBe("unknown");
  });

  it("derives card status semantics", () => {
    expect(getArtifactCardState("failed")).toEqual({
      status: "failed",
      label: "failed",
      isPending: false,
    });
    expect(getArtifactCardState("processing")).toEqual({
      status: "processing",
      label: "generating",
      isPending: true,
    });
    expect(getArtifactCardState(null)).toEqual({
      status: "ready",
      label: "ready",
      isPending: false,
    });
  });
});
