/**
 * How the agent uses the call tool. Plain text the agent reads directly;
 * the runtime attaches it as this interface's instructions.
 */
export const A2A_INSTRUCTIONS: string = `## Agent-to-agent calls
- Use \`a2a_call\` for exact domain-like agent ids (for example \`yeehaa.io\`, \`docs.rizom.ai\`, or \`save-it-regression.example\`). A domain-like id is bare text with a dot and no slash/protocol; \`.example\` test domains are still exact domain-like ids. For saved agents, the tool validates approval before network contact. For unsaved exact domains, it verifies the Agent Card over HTTPS and may perform a one-shot call without saving.
- Pass only an exact domain-like agent id to \`a2a_call\`. If the user provides an HTTPS URL, pass only its hostname as the agent id (for \`https://docs.rizom.ai/a2a\`, pass \`docs.rizom.ai\`). Never pass a full URL, a non-HTTPS URL, or a display name like \`Brain\`.
- If the user names an exact domain-like agent id such as \`yeehaa.io\`, \`docs.rizom.ai\`, or \`refusal-followup.example\`, call \`a2a_call\` directly with that id. Do not preflight with \`system_list\` or \`system_get\`; the tool reports structured errors such as invalid Agent Card, not approved, or archived.
- If the user asks you to ask, message, contact, hear what an exact domain-like agent id has to say, or ask that agent for its own skills/capabilities, treat that as an agent call request first and call \`a2a_call\` in the same turn. Do not stop after listing the agent, drafting the question, searching general content locally, or reading saved agent entity metadata.
- After \`a2a_call\` returns within a turn, answer that turn from its response. Do **not** supplement with \`system_get\` (or any other read tool) on the agent entity, unless the user explicitly asks for directory/profile details about the agent itself.
- Do not create, capture, or generate a note containing the user's question in the same turn as an agent contact request. The user asked to ask the agent, not to persist the question.
- If \`a2a_call\` succeeds for an unsaved one-shot domain, you may offer to save/connect that agent for future calls, but do not auto-save it.
- If \`a2a_call\` fails because auth, re-authentication, network, invalid Agent Card, or the remote agent is unavailable, report that failure directly. Do not say the agent was saved, connected, or may need to be saved/connected first. If useful, offer to add the agent contact using the word "add". Do not answer from memory, local docs, onboarding docs, or general knowledge; the requested agent was the source.
- Each new turn that asks the same exact domain-like agent id something — including short follow-ups like "what skills does it have", "and what about X", "tell me more" — is a **new** contact request and needs its **own** fresh \`a2a_call\`. Do not assume the previous turn's agent response already covers a new question, and do not substitute \`system_list\`/\`system_get\` or a no-tool answer for the fresh call. If the previous turn targeted an exact domain-like id such as \`yeehaa.io\`, use that same id again for the follow-up even if the previous response was a refusal or error; let \`a2a_call\` validate the current directory state again.
- When the user provides an HTTPS URL for an agent, use its hostname as the exact domain-like id for \`a2a_call\`; the runtime verifies/contact over HTTPS. If the user provides a non-HTTPS URL, ask for the HTTPS agent URL or exact domain-like id instead.
- If the user refers to an agent by name, first make sure that name resolves to exactly one saved agent id. If multiple saved agents could match, ask a concise clarification question naming the matching saved agent ids and do not call any agent yet. Never choose the first match.
- After asking that clarification question, end the turn. Do not call \`a2a_call\` later in the same turn.
- If \`a2a_call\` reports that an exact domain-like agent id cannot be verified, tell the user the agent could not be verified/contacted. Do not create a wish, reminder, todo, note, fallback task, or any new entity.
- For non-HTTPS URLs and ambiguous display names, do not call \`a2a_call\`; ask the user for the HTTPS agent URL, exact domain-like id, or a clarification first.
- Use \`agents_connect\`, not generic entity creation, when the user explicitly asks you to add, save, or connect an agent contact.
- If the target agent is discovered but not approved yet, do not call it and do not create a wish. Tell the user it must be approved first.`;
