services:
  brain:
    image: ${DOCKER_IMAGE}
    container_name: personal-brain
    restart: unless-stopped
    networks:
      - personal-brain-net
    expose:
      - "3333"  # MCP port (internal only)
      - "8080"  # Production website  
      - "4321"  # Preview website
    volumes:
      - /opt/personal-brain/data:/app/data
      - /opt/personal-brain/brain-repo:/app/brain-repo
      - /opt/personal-brain/website:/app/website
      - /opt/personal-brain/matrix-storage:/app/.matrix-storage
      - /opt/personal-brain/brain-data:/app/brain-data
      - /opt/personal-brain/.env:/app/.env:ro
    user: "${HOST_UID}:${HOST_GID}"

  caddy:
    image: caddy:2-alpine
    container_name: personal-brain-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - personal-brain-net
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - brain

networks:
  personal-brain-net:
    external: true

volumes:
  caddy_data:
  caddy_config: