import { describe, expect, it } from "bun:test";
import { mkdtemp, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import packageJson from "../package.json";
import { initPilotRepo } from "../src/init";

describe("initPilotRepo", () => {
  it("creates the private rover-pilot repo skeleton", async () => {
    const root = await mkdtemp(join(tmpdir(), "brains-ops-init-"));
    const repo = join(root, "rover-pilot");

    await initPilotRepo(repo);

    expect(existsSync(join(repo, "pilot.yaml"))).toBe(true);
    expect(existsSync(join(repo, "cohorts"))).toBe(true);
    expect(existsSync(join(repo, "users"))).toBe(true);
    expect(existsSync(join(repo, "views", "users.md"))).toBe(true);
    expect(existsSync(join(repo, "docs", "onboarding-checklist.md"))).toBe(
      true,
    );
    expect(existsSync(join(repo, "docs", "operator-playbook.md"))).toBe(true);
    expect(existsSync(join(repo, "package.json"))).toBe(true);
    expect(existsSync(join(repo, ".github", "workflows", "build.yml"))).toBe(
      true,
    );
    expect(existsSync(join(repo, ".github", "workflows", "deploy.yml"))).toBe(
      true,
    );
    expect(
      existsSync(join(repo, ".github", "workflows", "reconcile.yml")),
    ).toBe(true);
    expect(existsSync(join(repo, "deploy", "kamal", "deploy.yml"))).toBe(true);
    expect(existsSync(join(repo, "deploy", "Dockerfile"))).toBe(true);
    expect(existsSync(join(repo, ".kamal", "hooks", "pre-deploy"))).toBe(true);
    expect(existsSync(join(repo, "README.md"))).toBe(true);

    const pilotYaml = await readFile(join(repo, "pilot.yaml"), "utf8");
    expect(pilotYaml).toContain("schemaVersion: 1");
    expect(pilotYaml).toContain("model: rover");
    expect(pilotYaml).toContain("githubOrg: <github-org>");
    expect(pilotYaml).toContain("contentRepoPrefix: rover-");
    expect(pilotYaml).toContain("aiApiKey: AI_API_KEY");

    const usersTable = await readFile(join(repo, "views", "users.md"), "utf8");
    expect(usersTable).toContain(
      "<!-- generated by brains-ops; do not edit -->",
    );
    expect(usersTable).toContain("| alice | cohort-1 | rover | core |");
    expect(usersTable).toContain("| handle | cohort | model | preset |");

    const repoPackageJson = await readFile(join(repo, "package.json"), "utf8");
    expect(repoPackageJson).toContain(
      `"@brains/ops": "${packageJson.version}"`,
    );
    expect(repoPackageJson).toContain('"private": true');

    const buildWorkflow = await readFile(
      join(repo, ".github", "workflows", "build.yml"),
      "utf8",
    );
    expect(buildWorkflow).toContain("docker/build-push-action@v6");
    expect(buildWorkflow).toContain("brainVersion");
    expect(buildWorkflow).toContain(
      "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}",
    );
    expect(buildWorkflow).not.toContain("TODO:");

    const deployWorkflow = await readFile(
      join(repo, ".github", "workflows", "deploy.yml"),
      "utf8",
    );
    expect(deployWorkflow).toContain("workflow_dispatch:");
    expect(deployWorkflow).toContain("handle:");
    expect(deployWorkflow).toContain("bun install");
    expect(deployWorkflow).toContain("bunx brains-ops onboard");
    expect(deployWorkflow).not.toContain("repository: rizom-ai/brains");
    expect(deployWorkflow).not.toContain(".brains/packages/brains-ops");
    expect(deployWorkflow).toContain("BRAIN_YAML_PATH");
    expect(deployWorkflow).not.toContain("TODO:");

    const reconcileWorkflow = await readFile(
      join(repo, ".github", "workflows", "reconcile.yml"),
      "utf8",
    );
    expect(reconcileWorkflow).toContain("pilot.yaml");
    expect(reconcileWorkflow).toContain("cohorts/**");
    expect(reconcileWorkflow).toContain("users/*.yaml");
    expect(reconcileWorkflow).toContain("bun install");
    expect(reconcileWorkflow).toContain("bunx brains-ops reconcile-all");
    expect(reconcileWorkflow).not.toContain("repository: rizom-ai/brains");
    expect(reconcileWorkflow).toContain("git push");
    expect(reconcileWorkflow).not.toContain("TODO:");

    const dockerfile = await readFile(
      join(repo, "deploy", "Dockerfile"),
      "utf8",
    );
    expect(dockerfile).toContain("ARG BRAIN_VERSION");
    expect(dockerfile).toContain("bun add @rizom/brain@$BRAIN_VERSION");
    expect(dockerfile).toContain("brain start");

    const deployConfig = await readFile(
      join(repo, "deploy", "kamal", "deploy.yml"),
      "utf8",
    );
    expect(deployConfig).toContain("service: rover");
    expect(deployConfig).toContain("app_port: 3333");
    expect(deployConfig).toContain("path: /health");
    expect(deployConfig).toContain("/opt/brain.yaml:/app/brain.yaml");

    const preDeployHookPath = join(repo, ".kamal", "hooks", "pre-deploy");
    const preDeployHook = await readFile(preDeployHookPath, "utf8");
    expect(preDeployHook).toContain("BRAIN_YAML_PATH");
    expect(preDeployHook).toContain("/opt/brain.yaml");
    const preDeployHookStat = await stat(preDeployHookPath);
    expect(preDeployHookStat.mode & 0o111).toBeGreaterThan(0);

    const readme = await readFile(join(repo, "README.md"), "utf8");
    expect(readme).toContain("brains-ops init");
    expect(readme).toContain("brains-ops render");
    expect(readme).toContain("single operator-owned repo");
  });

  it("preserves existing human-edited files on rerun", async () => {
    const root = await mkdtemp(join(tmpdir(), "brains-ops-init-"));
    const repo = join(root, "rover-pilot");

    await mkdir(repo, { recursive: true });
    await writeFile(
      join(repo, "pilot.yaml"),
      "schemaVersion: 1\nbrainVersion: 0.1.1-alpha.99\nmodel: rover\ngithubOrg: custom-org\ncontentRepoPrefix: rover-\ndomainSuffix: .rizom.ai\npreset: core\naiApiKey: CUSTOM_AI_API_KEY\n",
    );

    await initPilotRepo(repo);

    const pilotYaml = await readFile(join(repo, "pilot.yaml"), "utf8");
    expect(pilotYaml).toContain("githubOrg: custom-org");
    expect(pilotYaml).toContain("aiApiKey: CUSTOM_AI_API_KEY");
    expect(pilotYaml).not.toContain("<github-org>");
    expect(existsSync(join(repo, "views", "users.md"))).toBe(true);
  });
});
