import { describe, expect, it } from "bun:test";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import { writeUsersTable } from "../src/render-users-table";

async function createPilotRepo(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "rover-pilot-render-"));

  for (const [relativePath, content] of Object.entries(files)) {
    const filePath = join(root, relativePath);
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
  }

  return root;
}

describe("writeUsersTable", () => {
  it("renders desired-state markdown table to views/users.md", async () => {
    const root = await createPilotRepo({
      "pilot.yaml": `schemaVersion: 1
brainVersion: 0.1.1-alpha.14
model: rover
githubOrg: rizom-ai
contentRepoPrefix: rover-
domainSuffix: .rizom.ai
preset: core
aiApiKey: AI_API_KEY
gitSyncToken: GIT_SYNC_TOKEN
contentRepoAdminToken: CONTENT_REPO_ADMIN_TOKEN
mcpAuthToken: MCP_AUTH_TOKEN
agePublicKey: age1testpublickey
`,
      "users/alice.yaml": `handle: alice
discord:
  enabled: false
`,
      "users/bob.yaml": `handle: bob
discord:
  enabled: true
`,
      "cohorts/canary.yaml": `brainVersionOverride: 0.1.1-alpha.15
presetOverride: default
members:
  - alice
`,
      "cohorts/steady.yaml": `members:
  - bob
`,
      "users/alice/brain.yaml": "brain: rover\npreset: default\n",
    });

    await writeUsersTable(root, {
      resolveStatus(user) {
        if (user.handle === "alice") {
          return Promise.resolve({
            serverStatus: "ready",
            deployStatus: "ready",
            dnsStatus: "ready",
            mcpStatus: "failed",
          });
        }

        return Promise.resolve(undefined);
      },
    });

    const content = await readFile(join(root, "views/users.md"), "utf8");
    expect(content).toContain("<!-- generated by brains-ops; do not edit -->");
    expect(content).toContain(
      "| handle | cohort | model | preset | brainVersion | domain | contentRepo | discord | serverStatus | deployStatus | dnsStatus | mcpStatus |",
    );
    expect(content).toContain(
      "| alice | canary | rover | default | 0.1.1-alpha.15 | alice.rizom.ai | rover-alice-content | off | ready | ready | ready | failed |",
    );
    expect(content).toContain(
      "| bob | steady | rover | core | 0.1.1-alpha.14 | bob.rizom.ai | rover-bob-content | on | unknown | unknown | unknown | unknown |",
    );
  });
});
