import { describe, expect, it } from "bun:test";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import { writeUsersTable } from "../src/render-users-table";

async function createPilotRepo(files: Record<string, string>) {
  const root = await mkdtemp(join(tmpdir(), "rover-pilot-render-"));

  for (const [relativePath, content] of Object.entries(files)) {
    const filePath = join(root, relativePath);
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, content);
  }

  return root;
}

describe("writeUsersTable", () => {
  it("renders desired-state markdown table to views/users.md", async () => {
    const root = await createPilotRepo({
      "pilot.yaml": `schemaVersion: 1
brainVersion: 0.1.1-alpha.12
model: rover
githubOrg: rizom-ai-pilot
repoPrefix: rover-
contentRepoSuffix: -content
domainSuffix: .rover.example.com
preset: core
`,
      "users/alice.yaml": `handle: alice
discord:
  enabled: false
`,
      "users/bob.yaml": `handle: bob
discord:
  enabled: true
`,
      "cohorts/canary.yaml": `brainVersionOverride: 0.1.1-alpha.13
presetOverride: pro
members:
  - alice
`,
      "cohorts/steady.yaml": `members:
  - bob
`,
      "users/alice/brain.yaml": "brain: rover\npreset: pro\n",
    });

    await writeUsersTable(root, {
      resolveStatus(user) {
        if (user.handle === "alice") {
          return Promise.resolve({
            repoStatus: "ready",
            deployStatus: "ready",
            dnsStatus: "ready",
            mcpStatus: "failed",
          });
        }

        return Promise.resolve(undefined);
      },
    });

    const content = await readFile(join(root, "views/users.md"), "utf8");
    expect(content).toContain("<!-- generated by rover-pilot; do not edit -->");
    expect(content).toContain(
      "| handle | cohort | model | preset | brainVersion | domain | repo | contentRepo | discord | repoStatus | deployStatus | dnsStatus | mcpStatus | snapshotStatus |",
    );
    expect(content).toContain(
      "| alice | canary | rover | pro | 0.1.1-alpha.13 | alice.rover.example.com | rover-alice | rover-alice-content | off | ready | ready | ready | failed | present |",
    );
    expect(content).toContain(
      "| bob | steady | rover | core | 0.1.1-alpha.12 | bob.rover.example.com | rover-bob | rover-bob-content | on | unknown | unknown | unknown | unknown | missing |",
    );
  });
});
