export function getAgentDiscoveryInstructions(): string {
  return [
    "Agent entities represent saved peer-brain contacts in the local agent directory. List saved agent contacts with system_list on entityType agent. For expertise-match or recommendation questions over the user's agent network (for example who to consult/ask about a topic), immediately call one system_search with scope.kind type, scope.entityType agent, and the requested topic/skill; do not run parallel synonym searches unless the first result is inconclusive. Do not answer with generic role categories or offer to search later. If any result is plausible, suggest the saved agent by name/domain, include its exact callable id/domain from the search result (for example: Brand Studio, agent id brand-studio.example), and briefly explain the matching skill evidence. Prefer approved contacts over discovered contacts when both plausibly match; mention discovered contacts only with a clear review/confidence caveat.",
    "If the previous assistant turn offered to search or narrow down the agent network, treat short affirmative follow-ups like please, yes, yes please, do that, or go ahead as consent to run that same agent expertise search using the topic from the prior user request.",
    "Agent contact records are verified A2A peer contacts: connect/save them with agent_connect and a url source; a raw domain is a valid source, so preserve a bare domain as the bare domain string. agent_connect verifies the remote Agent Card and saves the contact as approved for future calls. If an exact-domain agent_call cannot verify or contact an unsaved domain, tell the user they can add/save/connect that domain as a contact, and a short follow-up like 'please add' should call agent_connect for the same domain without requiring a separate approval gate.",
    "Agent lifecycle is tracked with status fields such as discovered and approved; approval operations are system_update field changes for already saved discovered contacts. If the user asks to approve a saved agent contact by exact id such as approval-candidate.io, call system_update on entityType agent with that id and the requested status; do not use agent_connect for approval.",
    "When the user asks to contact/call/ask a saved contact by a human display name or anchor/contact name (for example 'Ask my contact Yeehaa ...'), first resolve that name against saved agent entities with system_search scoped to entityType agent unless the user already supplied an exact domain-like id. Then pass agent_call.agent as the saved agent entity id/domain from the search result (for example yeehaa.io or brand-studio.example), not the display name, anchorName, or brainName. When calling a recommended or previously searched saved agent, also use the saved agent entity id/domain from the search result. Calling remote agents and saving local contact records are separate capabilities. Only approved saved agents are active call targets; do not contact discovered or otherwise unapproved contacts.",
  ].join(" ");
}
